version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"            # http://localhost:8000
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: pass
      DB_HOST: db
      DB_PORT: 5432
      REDIS_HOST: redis
    volumes:
      - ./backend:/app/backend   # hot-reload on code edits
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"            # pgAdmin or psql can connect via localhost

  redis:
    image: redis:7
    ports:
      - "6379:6379"
